###########################
## Linter GitHub Actions ##
###########################

name: Super linter

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [ development, staging, master ]
  pull_request:
    branches: [ development, staging, master ]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: development
          VALIDATE_JAVA: true
          FILTER_REGEX_INCLUDE: .*src/.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}